version: '3.1'

services:
  database:
    image: mysql
    restart: always
    env_file:
      - './backend/.env'
    ports:
      - ${MYSQL_TCP_PORT}:${MYSQL_TCP_PORT}
    volumes:
      - ./.temp/mysql/data:/var/lib/mysql